### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [ryotaroinagaki/Soramix2English#73]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
READMEを拝見し、挙動の確認を行いました。LGTMです。

## 静的コードチェックが入っている
概ね良いかと思いました。コメントアウトしているコードは削除しておきましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・結論から申しますと、十分な技術力を示せるものには達していないと思いました。
・その他の機能の書かれている「オートコンプリート機能」「レコメンド機能」「解答閲覧後、音声認識による、自分の発音の確認」の順で優先的に実装しましょう。
・collectionやmemberなどを使用しているルーティングをresourceベースに近づけられないか検討&修正を行いましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・TOPページの「1.ユーザー登録しよう！」ですが、実際のフォームかと勘違いしたりしたので、トップページに見せ方をもう少し工夫すると、ユーザーが戸惑わないかと思います。
・クイズ一覧のカード部分が横幅によっては重なっていたりしたので調整しましょう。（クイズ選択画面も同様です）
・マイページのプロフィール編集ボダンですが、フッターと近すぎるかと思うので調整しましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by ryotaroinagaki** [comment]
早速のレビューありがとうございます。
ご指摘頂いた内容をもとにissueを作成しました。
本リリースは10/6頃を予定しています。

ご確認よろしくお願いします！

**Comment by Tsuchiya2** [comment]
ご回答及びご対応ありがとうございます。
引き続き開発頑張ってください。
